- name: Install Restic and jq
  when: ansible_os_family == 'Debian'
  ansible.builtin.apt:
    update_cache: yes
    name:
      - restic
      - jq

- name: Create directories for Restic
  loop:
    - "{{ restic.prefix.bin }}"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: "{{ root_group }}"
    mode: "0755"
