- name: Install Restic and jq
  when: ansible_distribution == 'Ubuntu'
  apt:
    name:
      - restic
      - jq

- name: Create directories for Restic
  loop:
    - "{{ restic.prefix.bin }}"
  file:
    path: "{{ item }}"
    state: directory
